# Generated by Django 3.1.3 on 2023-08-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.IntegerField(default=0),
        ),
    ]
